<?php

namespace Modules\Payment\database\seeders;

use Illuminate\Database\Seeder;
use Modules\Order\Domain\Models\Order;
use Modules\Payment\Domain\Models\Payment;
use Modules\Order\Enums\PaymentStatus;
use Illuminate\Support\Str;

class PaymentDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Find Orders that are marked PAID but have NO Payment record
        // This is a "Cleanup" seeder to ensure data integrity
        $orphanPaidOrders = Order::where('payment_status', PaymentStatus::PAID)
            ->whereDoesntHave('payments')
            ->get();

        if ($orphanPaidOrders->isEmpty()) {
            return;
        }
        $this->command->getOutput()->progressStart($orphanPaidOrders->count());

        foreach ($orphanPaidOrders as $order) {
            $method = fake()->randomElement(['momo', 'vnpay', 'credit_card', 'bank_transfer']);
            $paidAt = $order->ordered_at->copy()->addMinutes(rand(5, 60));

            Payment::create([
                'uuid' => (string) Str::uuid(),
                'order_id' => $order->id,
                'method' => $method,
                'amount' => $order->grand_total, 
                'currency' => 'VND',
                'status' => 'paid',
                'paid_at' => $paidAt,
                'created_at' => $paidAt,
                'transaction_id' => strtoupper($method) . '-' . Str::random(10),
                'payment_data' => ['message' => 'Auto-generated by PaymentSeeder'],
            ]);

            $this->command->getOutput()->progressAdvance();
        }

        $this->command->getOutput()->progressFinish();
    }
}